### ISSUE TITLE
onnx-tensorflow has frontend, what is the purpose of this repository

### ISSUE THREAD

**Issue by fumihwh** [onnx/tensorflow-onnx#1]
As title, do you want to separate it from onnx-tensorflow and move to here?
Maybe `Tensorflow Backend for ONNX` misleads. Actually, it contains frontend part.
I think we don't need this repository.

**Comment by prasanthpul** [comment]
This repository contains the converter from TensorFlow to ONNX. onnx-tensorflow has the ONNX->TensorFlow converter.

**Comment by fumihwh** [comment]
@prasanthpul 
Thank you for reply.
As I said, `onnx-tensorflow` also has tensorflow->onnx converter. 
Maybe we should discuss and find a way to deal with this?

**Comment by prasanthpul** [comment]
Sure - please work with @guschmue

**Comment by tjingrant** [comment]
@prasanthpul @guschmue hi, I'm the maintainer of the ONNX-Tensorflow project. I think there may be some miscommunication. Just like onnx-caffe2 is not just an onnx->caffe2 converter, onnx-tensorflow is not just an onnx->tensorflow converter. 

But as of now, I think the best way to deal with this (and minimize damage to hardworking contributors both from our open community and from Microsoft) is to properly recognize everyone's contribution and try to put our work together and jointly manage them.

**Comment by guschmue** [comment]
yes, I'm all for it. There is plenty of functionality missing to make this work for model developers. 
Lets figure how we go about this.

**Comment by tjingrant** [comment]
Taking a quick peek at your README, it looks like it has a very neat architecture. Our existing implementation is quite straightforward: it starts with your step 4. I believe it should be quite doable to merge our work together with minimal damage. As you can see, the majority of our frontend code is about individual operation-level conversion. 

So essentially, there are the following things that needs to be done to merge our work:
1. We have a very simple pre-processing before Step. 4 so maybe we should use your pre-processing (step 1-4). This step is somehow tricky because we also like to keep some codes shared between frontend and backend (like some shared trivial conversion).
2. We can then merge our individual operation level conversion ( basically from https://github.com/onnx/onnx-tensorflow/blob/master/onnx_tf/frontend.py and https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/tfonnx.py).
3. Obviously merge tests and documentations.

Let us not be discouraged by this accident since there should be plenty of code that are re-usable from both our projects. 

@fumihwh @guschmue I have added both of you as collaborators for onnx-tensorflow repo. You are welcomed (and please do if you can...) to pick any of the work items above and go ahead with it. I'll do the rest of the things if no one picks up.

**Comment by guschmue** [comment]
I think the first thing we need to decide if there should be onnx->tensorflow and tensorflow->onnx or if there is one that does it all.
I'm not so worried about individual ops, much more about subgraphs, nhwc transposes and the capability to compose ops easy so we can fill in some tensorflow ops that onnx doesn't have equals for.

**Comment by tjingrant** [comment]
I'm for one repo that does it all b/c:
1. Both frontend and backend are relatively small in size, which means putting them in one place adds little burden for user in either direction. In addition, it reduces possible user confusion about which way does it go.
2. It mirrors https://github.com/onnx/onnx-caffe2 and it is indeed the way the name "onnx-[some framework]" is supposed to mean. In fact, as you can see, tensorflow-onnx is the only project in ONNX directory that starts with a target framework name... 
3. I do share your concern especially after spending lots of time debugging similar stuff from the backend and I think your way of handling should be adopted. About NHWC transpose, we are also pushing forward this PR (named axis, https://github.com/onnx/onnx/pull/443) to ensure correctness in our final converted product.

**Comment by prasanthpul** [comment]
@tjingrant since I was involved in the original discussions about sub-repo naming when onnx was setup, I wanted to mention that the intent was to allow both onnx-framework and framework-onnx repos depending on the direction of conversion. so tensorflow-onnx is valid name given the functionality.

**Comment by tjingrant** [comment]
Okay, that was quite unexpected given that no other repo has made such a precedent. But point taken, let me strike off number 2.

**Comment by guschmue** [comment]
Let me spend some quality time on onnx-tensorflow to see how this could be joined. 
First thing I can do is to add it as backend for testing,

**Comment by terrytangyuan** [comment]
Any updates on this?

**Comment by nbcsm** [comment]
close this issue since we decided to merge these 2 repo.
