### ISSUE TITLE
SSD mobilenetV2 conversion error

### ISSUE THREAD

**Issue by Zrufy** [onnx/tensorflow-onnx#1031]
How solve this error?

`2020-07-31 17:01:55,332 - WARNING - Cannot infer shape for Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/zeros: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/zeros:0`

**Comment by guschmue** [comment]
its just a warning that we don't know the shape of `zero`.
We print it because sometimes there are errors later in the conversion and its helpful to know about missing shapes, especially if a user reports some error and we don't have the model itself.
If that missing shape would be an issue would see some real error message later in the conversion.

**Comment by Zrufy** [comment]
@guschmue do you have any advice to bring this ssd from tensorflow to onnx?
https://github.com/pierluigiferrari/ssd_keras

**Comment by guschmue** [comment]
As far I can tell this is an old keras h5 checkpoint. You'd need to get this into a tensorflow frozen graph or a tensorflow saved-model so tf2onnx can load the checkpoint. Search for 'freeze keras model' should return some scripts to do this.

Easier might be to use [keras2onnx converter](https://github.com/onnx/keras-onnx) to convert directly from keras.

**Comment by guschmue** [comment]
we assume this is resolved.

**Comment by Zrufy** [comment]
i have this error not only in this case but with tensorflow object detection api.
