### ISSUE TITLE
Argument type mismatch

### ISSUE THREAD

**Issue by scottyyih** [onnx/tensorflow-onnx#1076]
In this line of code `flag, match_list_of_input = self._match_pattern(input_pattern, input_tensor, input_tensor)` in graph_matcher.py, why the second argument `input_tensor` is a tf.Tensor type argument?

**Comment by TomWildenhain-Microsoft** [comment]
Looks like a bug to me.  In this case, `input_tensor` comes from `pat = list(zip(op.inputs, possible_pattern_inputs))` and `for input_tensor, input_pattern in pat` so it is in fact an op not a tensor.  `input_tensor` should be renamed to `input_op`.  I don't know why self._match_pattern is being given the op twice and no tensor.  Eventually that "tensor" is stored in the `MatchResult` and can be retrieved using `get_tensor`.  The current codebase never calls `get_tensor` which is why all tests pass and there isn't an issue.

**Comment by TomWildenhain-Microsoft** [comment]
Is there any particular reason you were looking at this?

**Comment by scottyyih** [comment]
> Is there any particular reason you were looking at this?

Thank you for your reply. Nothing particular. I just try to view and understand the source code.

**Comment by TomWildenhain-Microsoft** [comment]
This was actually fixed a while ago.
