### ISSUE TITLE
Problem converting Conv2dTranspose in TF2

### ISSUE THREAD

**Issue by guanaco** [onnx/tensorflow-onnx#1101]
**Describe the bug**
When trying to convert tf2 saved model with Conv2DTranspose, it's converted to complex operations instead of a single operation. (See screenshot for more details.

**Urgency**
none

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- Tensorflow Version: tensorflow                2.2.0           gpu_py38hb782248_0  (installed with conda)
- Python version: 3.8.5 (conda)

**To Reproduce**
See python code below:
```python
import tensorflow as tf
import numpy as np
import os
import subprocess

def tf_saved_model_to_onnx(saved_model_folder, onnx_path, opset=11):
    command = f'python3 -m tf2onnx.convert --saved-model {saved_model_folder} --output {onnx_path} --opset {opset}'
    result = subprocess.run(command, shell=True, check=True)
    if result.returncode == 0:
        print('--- frozen graph converted to onnx model', onnx_path)
    else:
        print('--- failed({}) to {} convert to onnx model'.format(result.returncode, saved_model_folder))

if __name__ == '__main__':
    filters = 256
    x = np.random.random((1, 17, 20, filters))
    model = tf.keras.Sequential(
        [tf.keras.layers.Convolution2DTranspose(filters, 3)]
    )
    y = model(x, training=False)
    print(f'--- y shape: {y.shape}')

    model_foler = '../model'
    tf_name = 'deconv'
    tf_folder = os.path.join(model_foler, tf_name)
    onnx_name = tf_name + '.onnx'
    onnx_path = os.path.join(model_foler, onnx_name)
    
    tf.saved_model.save(model, tf_folder)
    tf_saved_model_to_onnx(tf_folder, onnx_path)
```

**Expected behavior**
One single Conv2DTranspose will be converted to one operation in onnx accordingly.

**Screenshots**
![deconv](https://user-images.githubusercontent.com/639019/93011491-ee4acb00-f596-11ea-8962-1b235fbe266f.png)

**Additional context**
none

**Comment by guschmue** [comment]
In tensorflow the graph looks like below - it is more than a single op:
![image](https://user-images.githubusercontent.com/22941064/93023611-fdd11080-f5a4-11ea-9b6e-fd99a0788758.png)

The onnx graph looks larger because:
1. tensorflow / Conv2DBackpropInput is in NHWC and we need to wrap it with Transpose to convert it to NCHW. In larger graphs we can mostly optimize those transposes away bot not if there is only a single op.
2. onnx does not have Pack() and and the right part of the graph is how we map Pack() to onnx. While this looks costly it only is a calculation on the shape and cheap.
3. onnx ConvTranspose has a different interface than ConvTranspose/Conv2DBackpropInput - the bottom on the graph reflects this.

The onnx graph is not great but is not unexpected. In real models 1 and 2 should not show.
