### ISSUE TITLE
When trying to convert keras -> onnx -> tf model, export_graph method fails with Invalid value in tensor used for shape: -3 inside _create_c_op method

### ISSUE THREAD

**Issue by daganida88** [onnx/tensorflow-onnx#1157]
I have a Keras model which I want to transform to PB format so I can use it in TF Serving.
After converting the model to onnx and from onnx to pb, I get the following error message when I invoke export_graph.
Invalid value in tensor used for shape: -3 (inside _create_c_op method)
    onnx_model = keras2onnx.convert_keras(model, model.name)
    tf_rep = prepare(onnx_model)  # prepare tf representation
    tf_rep.export_graph("/path/to/output/graph")  ---> This is where I get the exception.

Any ideas?? Thanks 👍

**Comment by TomWildenhain-Microsoft** [comment]
This repo is for tf2onnx which goes from tensorflow to onnx, not the other way around.  To go from Keras to Tensorflow you don't actually have to go through ONNX since Keras already uses Tensorflow as a backend.  Calling .save() on the keras model will create a TF saved_model.  That said, if you are deploying your model you may find that going to ONNX gives better performance if you run the ONNX model directly in ONNX Runtime: https://github.com/Microsoft/onnxruntime
`pip install onnxruntime`
```
import onnxruntime as rt
inputs = { "inp_1:0": np.zeros(some_shape), ... }
output_names = ["Identity:0", ...]
m = rt.InferenceSession("path/to/model.onnx")
results = m.run(output_names, inputs)
```

**Comment by guschmue** [comment]
If there is still some issue, keras2onnx is here:
 https://github.com/onnx/keras-onnx/tree/master/keras2onnx
