### ISSUE TITLE
Inference time is more than 8 times slower after transforming tflite model to onnx model

### ISSUE THREAD

**Issue by sniper0110** [onnx/tensorflow-onnx#1391]
**Describe the bug**
I have a tflite model that runs with an inference speed of **21ms/image**. 
I transformed the model to an onnx model using this command:
`python -m tf2onnx.convert --opset 13 --output "models/ONNXModels/tflite_model_af_2.onnx" --tflite "models/TFLiteModels/my_relu_model_optimized.tflite" --inputs-as-nchw serving_default_image:0`

With the new onnx model, the inference speed is **177ms/image**.

From what I understood, tensorflow uses NHWC by default and ONNX uses NCHW. This causes ONNX to add some Reshape layers to change the shape of different layers. But by adding the flag : `--inputs-as-nchw serving_default_image:0` it's supposed to not add those Reshape layers right?

From my understanding, those added Reshape layers are the reason for this extra time of computation. But since I added the flag mentioned above, those layers should't be added and the speed of inference should not be affected, correct? Or am I missing something?

**Urgency**
We have models that we want to deploy asap in my company so it's urget.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bits
- Tensorflow Version: '2.3.0'
- Python version: 3.8.5

**To Reproduce**
To reproduce this, you can take this 
[tflite model](https://github.com/onnx/tensorflow-onnx/files/6115029/my_relu_model_optimized.zip) and transform it using the command I shared above. Then, you can test both models on a random input.

**Additional context**
I tried converting my tflite model with and without `--inputs-as-nchw serving_default_image:0` and it's not changing much in terms of inference speed. 
I used Netron and I looked at the transformed models with and without `--inputs-as-nchw serving_default_image:0`. I noticed that when I used this flag some Reshape layers disappeared and others still exist.

**Comment by TomWildenhain-Microsoft** [comment]
Hi @sniper0110, I ran the model on my machine and I get **8.1 ms for tflite** and **7.7 ms for onnxruntime**.  I got this result without the --inputs-as-nchw flag using **onnxruntime 1.6.0** on CPU.

A few questions:
- Are you running the model on CPU or GPU?  (make sure it is the same for both TF and onnx)
- What version of onnx runtime are you using?
- Are you using a custom-compiled tflite, or the stock one from tf?

A full `pip list` might be helpful.

You can determine which ops are taking the most time using this profiling tool.  Read the comment at the top of the file for instructions:
https://github.com/microsoft/onnxconverter-common/blob/master/onnxconverter_common/perfstats.py

The inputs-as-nchw might remove a single transpose at the top of the graph, but in your case this transpose is already being optimized into a reshape and is likely of negligible cost (profiling will tell).  I would be much more concerned about the loop in your model, since onnxruntime sometimes has trouble with loop efficiency.

Here are the models and perf testing script I have:
https://www.dropbox.com/s/gwd68v97m18r88o/relu_perf.zip?dl=1

**Comment by sniper0110** [comment]
Thank you for your answer @TomWildenhain-Microsoft !
I actually found the source of why I was having these large inference times. It has nothing to do with ONNX nor ORT.
In fact, I was measuring the time for processing images using **time.process_time()**. This in fact gives those time values that I mentioned above. When I use **time.time()** or **time.perf_counter()** I get results closer to yours. 

Now, I am trying to find out what's the difference between these functions for computing time.

Thanks for your answer and for sharing that profiling tool. It will be useful to me in the future.
