### ISSUE TITLE
Quantize layer disapeared when convert tensorflow QAT to ONNX QAT

### ISSUE THREAD

**Issue by Phincle** [onnx/tensorflow-onnx#1394]
**tensorflow QAT model like:**
【model 1】
                 [data]                                                  [weights]
                      |                                                            |
[FakeQuantWithMinMaxVars]         [FakeQuantWithMinMaxVars]
                                         \                /
                                            [ conv2d ]

**I hope it to be onnx QAT model like this after convert:**
【model 2】
                 [data]             [weights]
                      |                        |
[QuantizeLinear]         [QuantizeLinear]
                      |                        |
[DequantizeLinear]         [DequantizeLinear]
                        \                /
                          [ conv2d ]

**But it turned to be like:**
【model 3】
                 [data]           
                      |                   
[QuantizeLinear]        
                      |                  
[DequantizeLinear]       
                        \                
                          [ conv2d ]

Seems like weight has const folded .
I noticed that there is an arg in tf2onnx.convert :  
> --fold_const          Deprecated. Constant folding is always enabled.

Does this have anything to do with it?

please help, thanks.

**Comment by TomWildenhain-Microsoft** [comment]
Yes, it appears constant folding is eliminating that node, changing the pattern Const -> QuantizeLinear -> DequantizeLinear into a single Const.  Why do you want this pattern to be left unfolded?  I could understand wanting Const -> DequantizeLinear since the quantized representation might be smaller, but Const -> QuantizeLinear -> DequantizeLinear will store the weights as float32, which will be just as large as the folded version.

**Comment by guschmue** [comment]
I assume this is resolved.
