### ISSUE TITLE
different output from 1 command

### ISSUE THREAD

**Issue by hoaquocphan** [onnx/tensorflow-onnx#1417]
Dear All,

I would like to report the issue as below:

1/ download tensorflow model from tensorflow hub: https://tfhub.dev/google/imagenet/mobilenet_v1_025_128/classification/4
2/ use below command to convert saved model to onnx model:
`python3 -m tf2onnx.convert --saved-model imagenet_mobilenet_v1_025_128_classification_4/ --output imagenet_mobilenet_v1_025_128_classification_4.onnx --opset 12 --concrete_function 2 --inputs inputs:0[1,224,224,3] --inputs-as-nchw  inputs:0`

I install the tensorflow-onnx tool same version  on 2 Linux PC:
Tensorflow have same version 2.3.1

+ the first PC create output onnx with only 1 input: **inputs:0**
+ the second PC create output onnx with 2 inputs: **inputs:0** and  **batch_norm_momentum:0**

So could anyone explain with me, what is the issue?
so how can I remove the output batch_norm_momentum:0 in 2nd PC?

**Comment by TomWildenhain-Microsoft** [comment]
Are you certain that the versions of tf2onnx are the same, and the models are identical?  Check your environment's Lib/site-packages/tf2onnx line 398: https://github.com/onnx/tensorflow-onnx/blob/02feacfd4c5ead9c36e9c6de820e63542d6e12e3/tf2onnx/tf_loader.py#L398

`concrete_func = imported.__call__.get_concrete_function(*args, **kwargs)`
If it differs between the  computers, that would explain the difference.  Otherwise, double-check that you are using the same `--concrete_function` and the exact same version of the model.

**Comment by hoaquocphan** [comment]
Hi @TomWildenhain-Microsoft 

thanks for your reply.
+ I'm sure that the saved model are the same, because I copy from 1st PC to 2nd PC
+ the tf2onnx tool are the same and I check the code line as your comment, and it is the same.
+ I use the same concrete function as the command line in the previous post: **--concrete_function 2**

**Comment by TomWildenhain-Microsoft** [comment]
Can you upload both onnx models?  I'm wondering what value it is using for `batch_norm_momentum:0` if it is not an input.

**Comment by hoaquocphan** [comment]
Hi @TomWildenhain-Microsoft 

I just pushed 2 version of onnx model to my git folder https://github.com/hoaquocphan/shared_files

Please check and help me.

Thank you

**Comment by TomWildenhain-Microsoft** [comment]
Interesting, it looks like the input is completely unused.  Otherwise, the model looks the same.  We get the list of inputs from tensorflow, so maybe there is some nondeterminism there if an input is unused?  I'm not sure.

Can you try removing the `--inputs inputs:0[1,224,224,3]` flag?  Just use:
`python3 -m tf2onnx.convert --saved-model imagenet_mobilenet_v1_025_128_classification_4/ --output imagenet_mobilenet_v1_025_128_classification_4.onnx --opset 12 --concrete_function 2 --inputs-as-nchw inputs:0`

**Comment by hoaquocphan** [comment]
Hi @TomWildenhain-Microsoft 

the **batch_norm_momentum:0** input is unused and I want to remove it when convert from saved model to onnx model.
But I don't know why the 1st PC can remove it and the 2nd PC cannot remove it.

so could you give me some guide to remove this unused input?
or could you explain to me why there are the different output with the same tf2onnx tool and the same command line?

**Comment by hoaquocphan** [comment]
Hi @TomWildenhain-Microsoft 

I tried your command with out `--inputs inputs:0[1,224,224,3]` flag and the result on 2nd PC have 2 input as previous command, but the inputs:0 have the dynamic shape **float32[unk__507,3,unk__508,unk__509]**, your propose does not help to remove the unused input

the **batch_norm_momentum:0** input is unused and I want to remove it when convert from saved model to onnx model.
But I don't know why the 1st PC can remove it and the 2nd PC cannot remove it.

so could you give me some guide to remove this unused input?
or could you explain to me why there are the different output with the same tf2onnx tool and the same command line?

**Comment by TomWildenhain-Microsoft** [comment]
To remove the unused input you can edit the converted model with the onnx2py tool.  It will give you a human-readable python script that you can edit to make a new version of the model.

Clone this repo: https://github.com/microsoft/onnxconverter-common/blob/master/onnxconverter_common

Then do `python -m onnxconverter_common.onnx2py path/to/model.onnx desired/output/path/for/model.py`

As far as why the two computers give different outputs, I'm not sure but I have a guess.  The --input flag indicates which inputs you want to include, but additional inputs will still be included if needed.  The input must be used by a part of the graph that is optimized out later.  The order of attempted input removal vs optimization might be affecting the output.

**Comment by TomWildenhain-Microsoft** [comment]
On my machine, the input is removed.  To help debug, please add a line:
`logger.info("Placeholders to keep: %s", [n.name for n in related_nodes if n.type == "Placeholder"])`
after line 1519 in graph.py:
https://github.com/onnx/tensorflow-onnx/blob/02feacfd4c5ead9c36e9c6de820e63542d6e12e3/tf2onnx/graph.py#L1519

Then tell me what it prints.

**Comment by hoaquocphan** [comment]
HI @TomWildenhain-Microsoft 

It does not print your debug log,
I think that the **def delete_unused_nodes** wasn't called

**Comment by TomWildenhain-Microsoft** [comment]
That would be very surprising.  The calls leading to that function are:

https://github.com/onnx/tensorflow-onnx/blob/02feacfd4c5ead9c36e9c6de820e63542d6e12e3/tf2onnx/convert.py#L153
https://github.com/onnx/tensorflow-onnx/blob/02feacfd4c5ead9c36e9c6de820e63542d6e12e3/tf2onnx/tfonnx.py#L534
https://github.com/onnx/tensorflow-onnx/blob/02feacfd4c5ead9c36e9c6de820e63542d6e12e3/tf2onnx/tfonnx.py#L629

Can you determine which of these lines are being run?

**Comment by hoaquocphan** [comment]
Hi @TomWildenhain-Microsoft 


I'm so sorry for the previous post, I update the code in wrong directory.

I just realized that the tool tf2onnx will call script in the 1st directory: /home/hoaphan/.local/lib/python3.6/site-packages
if the 1st directory doesn't exist, it will call script in the 2nd directory: /usr/local/lib/python3.6/dist-packages/tf2onnx-1.9.0-py3.6.egg/tf2onnx/

When I run the tf2onnx tool, it call **/home/hoaphan/.local/lib/python3.6/site-packages/tf2onnx/tf_loader.py** with below code:
`concrete_func = imported.__call__.get_concrete_function(*sig)`
and create the onnx model with 2 inputs.

When I remove /home/hoaphan/.local/lib/python3.6/site-packages/tf2onnx, it call **/usr/local/lib/python3.6/dist-packages/tf2onnx-1.9.0-py3.6.egg/tf2onnx/tf_loader.py** with below code:
`concrete_func = imported.__call__.get_concrete_function(*args, **kwargs)`
and create the onnx model with only 1 input.

So could you explain more about above behavior?

**Comment by TomWildenhain-Microsoft** [comment]
Glad to hear tf2onnx is behaving consistently between machines.  Nondeterminism is a pain to debug.  

To avoid confusion with python environments, I recommend always using a virtual environment.  https://docs.python.org/3/library/venv.html

We recently updated the way we load signatures from TF.  Previously we were providing the positional arguments but not the kwargs.  In most models, this was fine since they didn't have any kwargs.  However, in some models it would pick the wrong signature as a result.  The signature it picks might have slightly different inputs/outputs.
