### ISSUE TITLE
opset for tutorial keras-restnet50.ipyn does not work when converting to tensorRT

### ISSUE THREAD

**Issue by hoangmt** [onnx/tensorflow-onnx#1420]
The current opset value of 13 is used to convert to onnx in [resnet50 tutorial](https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/keras-resnet50.ipynb). onnx model is generated however it fails when converting to tensorrt (using the command trtexec). Change opset to 7, it works. This is not intuitive as something works for old version (opset 7) should also work in new version (opset 13). Any explanation/guideline on how to use the opsets or just try all to see what works?

**Comment by guschmue** [comment]
what opset to use is hard to get right since some prefer the latest, some prefer something older.
The newer the opset the better we can map the tensorflow graph to onnx, in many cases more efficient.
opset-7 is really old and I would not use that one because all constants in the graph are also inputs which prevents runtimes from making various optimizations. opset-9 maybe the lowest I'd use - it fixed the input thing and has enough support to deal with most tensorflow models.

tensorrt supports opset-12 and as for I know their next version will support opset-13.

**Comment by guschmue** [comment]
I'll close this one, its not a real issue.
