### ISSUE TITLE
Could we use tf2onnx optimizer to simplify an existed onnx model?

### ISSUE THREAD

**Issue by wm2012011492** [onnx/tensorflow-onnx#1536]
**Describe the bug**
I'm looking for a stable and powerful graph optimizer for existed onnx models (i.e. generated by pytorch). In my opinion, the open-sourced [ONNX Optimizer](https://github.com/onnx/optimizer) often gets in trouble like segment fault (like unsupported op). tf2onnx optimizer seems a good candidate except that we are in lack of the load_from_onnx interface now. Since the ir of raw onnx graph and tf2onnx graph is pretty different, how could we implement the load_from_onnx()?

**Comment by guschmue** [comment]
Sure that would be possible. We have a script [here](https://github.com/onnx/tensorflow-onnx/blob/master/tools/onnx-experiments.py) that does some of what you'd need. Have not looked at that script for some time  but we can make sure it still works.
Of course most of the optimizations we do are because of things tensorflow needs but some might help. And of course one could add more to our optimizer.
Let me take a look at the script to make sure it still works.

**Comment by guschmue** [comment]
https://github.com/onnx/tensorflow-onnx/pull/1538

**Comment by wm2012011492** [comment]
Thanks guschmue. I'm able to run this script.

**Comment by guschmue** [comment]
let us know if this does any good for other converters.

**Comment by wm2012011492** [comment]
In my testing models, this optimizer is not suitable for graphs generated from PyTorch.

**Comment by guschmue** [comment]
Thanks for trying. Most of the patterns we handle are tensorflow specific so its not unexpected.
It is pretty easy for us to look for patterns and add a new optimizer so if there is something badly hurting we could look into adding some specific optimization .... let us know.
