### ISSUE TITLE
HashTableV2 ONNX Conversion error

### ISSUE THREAD

**Issue by sj120698** [onnx/tensorflow-onnx#1724]
**Describe the bug**
On converting tensorflow's pre-processing model for BERT i.e. bert_en_uncased_preprocess v3 (https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3) into ONNX model using tf2onnx from_saved_model API, the converted ONNX model fails ONNX checker function. Below is the error thrown on running the checker function over the ONNX model - 
![image](https://user-images.githubusercontent.com/36289274/133997574-07cf268c-b37d-42e2-ab67-0d1cee2f01fd.png)

     

**System information**
- OS Platform and Distribution: Windows 10
- Tensorflow Version: 2.6.0
- Python version: 3.8

**To Reproduce**
Convert the tensorflow model at https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3 to ONNX and run ONNX checker function over the model. I have attached the original tensorflow and converted ONNX models for reference.  

[attachments.zip](https://github.com/onnx/tensorflow-onnx/files/7195449/attachments.zip)
**Additional context**
While converting the tensorflow saved model into ONNX using from_saved_model API, I needed to import tensorflow_text additionally.

**Comment by TomWildenhain-Microsoft** [comment]
Hi @sj120698 

I was able to partially convert the model using the command line with:
`python -m tf2onnx.convert --saved-model "C:\Users\tomwi\Downloads\attachments\bert_en_uncased_preprocess_3" --output C:\Users\tomwi\Downloads\attachments\bert_en_uncased_preprocess_3\model.onnx --opset 14 
--extra_opset ai.onnx.contrib:1`

The `--extra_opset ai.onnx.contrib:1` flag is needed since the wordpiece tokenizer op doesn't exist in ONNX but has an implementation here: https://github.com/microsoft/onnxruntime-extensions

The result is missing two ops: CaseFoldUTF8 and NormalizeUTF8
You will probably need to implement those in onnxruntime-extensions, or cut them out of the graph if they aren't important.

**Comment by sj120698** [comment]
Hi @TomWildenhain-Microsoft 

Thanks for the help! I was able to convert the model using the command line :
`python -m tf2onnx.convert --saved-model bert_en_uncased_preprocess_3 --output model.onnx --opset 13 --extra_opset ai.onnx.contrib:1 --custom-ops CaseFoldUTF8:ai.onnx.contrib,NormalizeUTF8:ai.onnx.contrib`

Before inferring the ONNX model using python ORT InferenceSession, I added implementations for CaseFoldUTF8 and NormalizeUTF with @onnx_op decorator to register the custom-ops using onnxruntime-extensions (as referred to in https://github.com/microsoft/onnxruntime-extensions/blob/main/tutorials/tf2onnx_custom_ops_tutorial.ipynb). After doing this I am able to infer the model in python. 
 
I need to carry out the same in C++ as well, how can I add implementations for custom-ops and import onnxruntime-extensions in C++? Any reference would be of great help.

**Comment by TomWildenhain-Microsoft** [comment]
Well done!  I don't think we have a great tutorial on this so I'd recommend following the build instructions on onnxruntime-extensions.  Then once the build is working, look at a previous PR like this one: https://github.com/microsoft/onnxruntime-extensions/pull/148/files

If you run into issues, open an issue on that repo.
