### ISSUE TITLE
Understanding Einsum optimizations: Why alone equations aecd,abcd→acbe, acbe,aecd→abcd are decomposed?

### ISSUE THREAD

**Issue by buddhapuneeth** [onnx/tensorflow-onnx#1736]
**Describe the bug**
I am trying to convert TinyBert model to ONNX. In the process, with  latest tf2onnx: it was able to decompose einsum operators with  equations: `aecd,abcd→acbe, acbe,aecd→abcd` to low level ops like reduce, concat, gather and few other ops combinations. 

But with equations `abc,cde→abde, abcd,cde→abe` are left as such as einsum operator.

I tried to under the einsum_optimizer code it was bit overwhelming.

I would like to know Is there a way I can decompose all the einsum operators? including `abc,cde→abde, abcd,cde→abe`?

In general I would like to know which patterns are decomposed and which are not?

**Comment by TomWildenhain-Microsoft** [comment]
@xadupre

**Comment by xadupre** [comment]
These equations should work. This is what I got:
[decompose_einsum.zip](https://github.com/onnx/tensorflow-onnx/files/7289555/decompose_einsum.zip). Did you see any error message in the log? The operator einsum is not replaced due to a failure but it should appear in the log.

There is one case the optimizer does not do, it is diagonal sum is `ii->i` (or any equation duplicating the same letter in one term). Currently, there is no way to replace that operation more efficiently than einsum.

I used the following [notebook](http://www.xavierdupre.fr/app/mlprodict/helpsphinx/notebooks/einsum_decomposition.html) to produce those ONNX. I'll check with tf2onnx tomorrow.

**Comment by buddhapuneeth** [comment]
@xadupre Thanks for the response.
So, ideally except diagonal sum all einsum ops should be replaced?

In my logs, I didn't see any error but having this log:
`2021-10-05 07:49:07,633 - INFO - replacing einsum node 'StatefulPartitionedCall/model/self_attention/einsum/Einsum' by its decomposed version, name of the last node 'Identity__206'.`

**Comment by buddhapuneeth** [comment]
@xadupre  I am not seeing the exception you mentioned in the logs.
You can see full logs [here](https://drive.google.com/file/d/1X_NNLCQTuK2CgZc3jIX7z4rvWx41AMBl/view?usp=sharing).
I am trying to convert the Tiny Bert open-source model.
You can download that model [here](https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/2).
It will still have 8 einsum ops of patterns `abc,cde→abde, abcd,cde→abe`

Command used:
`python -m tf2onnx.convert --saved-model tb --output onnx_conv/model.onnx --opset 13 --v`

**Comment by xadupre** [comment]
That should not be an issue. I removed this line in #1739.
