### ISSUE TITLE
Attribute new_axis_mask not supported

### ISSUE THREAD

**Issue by rtm-1dyakonov** [onnx/tensorflow-onnx#1814]
I am trying to convert model created from TensorFlow Object Detection API from saved_model.pb to Onnx format. 

Unfortunately, next issue arrises: 
ValueError: StridedSlice: attribute new_axis_mask not supported

[Here ](https://drive.google.com/drive/folders/1h9DDU1x7mTV3edQXi4_cUCxIDGjuEmYA?usp=sharing)you can find my model either in saved_model and checkpoint formats.

**Comment by hwangdeyu** [comment]
Could you also provide a simple repro script python code?
This issue is related to this line [tensor.py#L785 StridedSlice](https://github.com/onnx/tensorflow-onnx/blob/5cd3b5b87ca8fbe38e90d2ecce6f9bda891792bf/tf2onnx/onnx_opset/tensor.py#L785).

**Comment by paulfauthmayer** [comment]
We were encountering the same issue when we tried to convert a model for which we wrote a custom layer. We were at first a bit confused because we nowhere explicitly used a StridedSlice but figured it was somewhere in the implementation of one  of the functions we used.

What fixed the issue for us, oddly enough, was to explicitly specify the newest opset. i.e.:

```python
    model = tf.keras.models.load_model(model_path)
    tf2onnx.convert.from_keras(model, output_path="model.onnx")
```

threw the same error @rtm-1dyakonov encountered above, but

```python
    model = tf.keras.models.load_model(model_path)
    tf2onnx.convert.from_keras(model, output_path="model.onnx", opset=15)
```

did not. I guess there may be something wrong with the default opset? Hope that helps :)

**Comment by fatcat-z** [comment]
Starting from opset 10, tf2onnx changed the way to handle StridedSlice op and accepted "new_axis_mask" attribute. So your solution is expected.

**Comment by Regenhardt** [comment]
Just newly installed tf2onnx and ran into this issue using default values. Should the default opset be set higher to avoid these problems? I'd say ML is a fast enough moving field currently that newer features should be preferred to compatibility for now.

**Comment by fatcat-z** [comment]
> Just newly installed tf2onnx and ran into this issue using default values. Should the default opset be set higher to avoid these problems? I'd say ML is a fast enough moving field currently that newer features should be preferred to compatibility for now.

Yes, there is another [PR](https://github.com/onnx/tensorflow-onnx/pull/1946) changing the default opset to 13. Please look forward to next release. Thanks!
