### ISSUE TITLE
ValidationError: No Op registered for TensorSliceDataset with domain_version of 15

### ISSUE THREAD

**Issue by Luisamnh** [onnx/tensorflow-onnx#1829]
**Describe the bug**

I'm sorry if this is a silly thing but I'm new at working with onnx.

I converted a tf model to onnx and I have this issue: 

ERROR - tf2onnx.tfonnx: Unsupported ops: Counter({'MapDataset': 4, 'TensorSliceDataset': 1, 'PaddedBatchDatasetV2': 1, 'DatasetToSingleElement': 1})

However, the model was successfully converted into onnx (i was able to load it with google collab)

The thing is when I try to convert it again into a tf model to test the optimization, I got this error:

ValidationError: No Op registered for TensorSliceDataset with domain_version of 15

==> Context: Bad node spec for node. Name: TensorSliceDataset OpType: TensorSliceDataset

**System information**
- Google collab
- Tensorflow Version: 2.7.0
- Python version: 3.7.12

**To Reproduce**
import onnx
import tf2onnx
import onnxruntime as rt
import numpy
import numpy as np
from onnx import AttributeProto, TensorProto, GraphProto
import warnings
from onnx_tf.backend import prepare
import tensorflow as tf
import tensorflow_addons as tfa
tf_model=onnx.load('__MODEL_PROTO.onnx')
tf_model = prepare(tf_model)

Onnx model files are located in here https://drive.google.com/drive/folders/1dq48slMbeGp7HizBLq-5b8LmSxQUA5AJ?usp=sharing 

**Screenshots**
model4.onnx is saved correctly 

Comand used to convert from tf to onnx:

python -m tf2onnx.convert --saved-model ./checkpoint/export/1621358231 --large_model --fold_const --opset 15 --verbose --debug --output model4.onnx

![image](https://user-images.githubusercontent.com/55853798/150420311-b8dea1b0-d9a5-45d1-890d-e2f98ae27206.png)

model is loaded but when I execute: tf_model = prepare(tf_model), I got the error

![image](https://user-images.githubusercontent.com/55853798/150420606-b745615f-9876-4e00-9a12-b60acb5f3c8a.png)

**Comment by fatcat-z** [comment]
This is expected.

There are still some tensorflow ops which could not be supported by ONNX, so tf2onnx has no idea to convert it to a correct ONNX op. But the strategy of tf2onnx for such case is: exporting the ONNX file successfully even there are any unknown ops in final ONNX file. And there will be some error messages during the converting.

Since these ops are not recognized by ONNX as well as onnxruntime, you will see the error message  "No Op registered for TensorSliceDataset with domain_version of 15" when you tried to inference this model by onnxruntime.

**Comment by fatcat-z** [comment]
It's been over 3 months, so closing this. Feel free to open a new one if the issue still exists.
