### ISSUE TITLE
tf2onnx creating empty and unuseable onnx model from SSD Mobilenet

### ISSUE THREAD

**Issue by ingenuityiot** [onnx/tensorflow-onnx#1921]
**Describe the bug**
When attempting to convert a TF SSD Mobilenet FPN model that has been trained via transfer learning from SavedModel to Onnx using tf2onnx  the optimizer outputs an empty model with just identity nodes as the place holder. 

**Urgency**
None this is for a personal project and its impacting my personal schedule only

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Enterprise Build 17763
- Tensorflow Version:  2.8.0
- Python version: 3.9.2

**To Reproduce**
The following commands were run (with model in ./mod) as well as trying opsets 9 through 13 and all with no difference
python -m tf2onnx.convert --tag serve --signature_def serving_default --saved-model ./mod --output model.onnx
python -m tf2onnx.convert  --saved-model ./mod --output model.onnx

**Screenshots**
The below screen shots show the log outputs of tf2onnx 
![image](https://user-images.githubusercontent.com/48560830/164946763-5543c165-d9e4-4426-b998-e32c39de3cac.png)

and the resultant model structure in Netron

![image](https://user-images.githubusercontent.com/48560830/164946704-ab10ba5b-d0e4-48d5-9a7e-d95284a18269.png)

**Additional context**
See source model attached
[model.zip](https://github.com/onnx/tensorflow-onnx/files/8548646/model.zip)

Any assistance would be appreciated

**Comment by FrancescoTosetti** [comment]
Hi @ingenuityiot  , probably you are using the TensorFlow 2 Object Detection API and you are providing the wrong Saved Model.

I think you have generated your model with this API:
`!python models/research/object_detection/export_tflite_graph_tf2.py \
    --trained_checkpoint_dir {YOUR CHECKPOINT DIR} \
    --output_directory {YOUR OUTPUT DIR} \
    --pipeline_config_path {YOUR PIPELINE.CONFIG}`
which is actually incorrect, since it is designed only for tflite conversion.

Try instead to convert your SSD model with 
`!python models/research/object_detection/exporter_main_v2.py \
    --trained_checkpoint_dir {YOUR CHECKPOINT DIR} \
    --output_directory {YOUR OUTPUT DIR} \
    --pipeline_config_path {YOUR PIPELINE.CONFIG}`

At this point, you can proceed with tf2onnx.convert, as you were doing.

**Comment by fatcat-z** [comment]
It's been over 3 months, so closing this. Feel free to open a new one if the issue still exists.
