### ISSUE TITLE
got nan output from converted model 

### ISSUE THREAD

**Issue by leqiao-1** [onnx/tensorflow-onnx#1988]
**Describe the bug**
Model converted from tensorflow graphdef got nan outputs.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows
- tf2onnx 1.11.1
- tensorflow 2.9.1
- onnx 1.12.0
- onnxruntime 1.11.1
- python 3.7

**To Reproduce**
[full_doran_frozen.zip](https://github.com/onnx/tensorflow-onnx/files/9025033/full_doran_frozen.zip)

model conversion command
```python -m tf2onnx.convert --graphdef full_doran_frozen.pb --output model.onnx --inputs title_lengths:0,title_encoder:0,ratings:0,query_lengths:0,passage_lengths:0,features:0,encoder:0,decoder:0,Placeholder:0  --outputs output_identity:0,loss_identity:0```

To run onnx and tensorflow model inference with given input data, run ```python inference.py```

**Screenshots**
![image](https://user-images.githubusercontent.com/61653207/176823267-1175c624-13bd-48f4-a65e-d2e1327fb3e1.png)

**Comment by hwangdeyu** [comment]
The root cause is mainly from `select` op implementation. The select will choose `Mul/Add` ops implementation firstly which  is faster than `Where` op.
After debugging, the model gets wrong `nan` in pb file:
![image](https://user-images.githubusercontent.com/10047193/188080376-ddc9485c-0d7e-421c-a5d6-d9a8544c8182.png)

The `less` op condition should be replaced in ONNX file：
![image](https://user-images.githubusercontent.com/10047193/188080747-cdea2536-e922-4ea1-9046-e55f08dfdc01.png)
