### ISSUE TITLE
Numpy data type not understood yet: bfloat16

### ISSUE THREAD

**Issue by josephrocca** [onnx/tensorflow-onnx#2064]
### Describe the feature request
Support for numpy data type bfloat16.

### Describe scenario use case
I'm trying to convert a pretrained VAE that uses this data type: https://colab.research.google.com/gist/josephrocca/b79bf29181290c5f20a4f6113fd034f2/stable_diffusion_jax-to-onnx.ipynb

**Edit:** Turns out, in this case, there was a float32 version of the weights available. Not sure how common that is, or how hard it is to upcast the weights in general. If this is usually not a problem (as it turned out not to be in this particular case), and if it's non-trivial to implement, then please feel free to close this issue.

**Comment by fatcat-z** [comment]
This error was thrown out by onnx.numpy_helper.from_array() method, and I've opened an [issue](https://github.com/onnx/onnx/issues/4618) to discuss it.

We could add some code as a workaround to avoid this error, adding the code below before [this line](https://github.com/onnx/tensorflow-onnx/blob/ddca3a5eb2d912f20fe7e0568dd1a3013aee9fa3/tf2onnx/tf_utils.py#L70):

    if tensor.dtype == types_pb2.DT_BFLOAT16:
        tensor.dtype = types_pb2.DT_HALF

Then your code could continue.

But, unfortunately, the model still could not be converted successfully because some unsupported ops:

ERROR:tf2onnx.tfonnx:Unsupported ops: Counter({'XlaConvV2': 36, 'XlaDotV2': 6, 'XlaGather': 6, 'PreventGradient': 1})

Regarding of those Xla*** ops, please refer to [here ](https://github.com/onnx/tensorflow-onnx/issues/1984#issuecomment-1176084553)for more information.

**Comment by josephrocca** [comment]
Thanks! I'll close this with the assumption that the issue you created in @onnx/onnx will track this problem, but please feel free to re-open if you'd like to track in this repo too.
