### ISSUE TITLE
Issue with converting subgraph of the ssd_mobilenet_v1_coco_2018_01_28 model

### ISSUE THREAD

**Issue by fanghuaqi** [onnx/tensorflow-onnx#519]
Hi, I want to convert a subgraph of [ssd_mobilenet_v1_coco_2018_01_28](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz). The subgraph first node is `Preprocessor/sub:0`, the last nodes are `concat:0,concat_1:0`, I am able to convert it through the following command:

 ```
python -m  tf2onnx/convert.py --input ssd_mobilenet_v1_coco_2018_01_28.pb --inputs Preprocessor/sub:0[1,300,300,3] --outputs concat:0,concat_1:0 --output ssd_mobilenet_v1_coco.onnx --verbose --opset 10
```

But I opened the converted model in Netron tool, and found the first node was not set to `Preprocessor/sub`, it still convert unused nodes for me, see image below :
![image](https://user-images.githubusercontent.com/1538922/57687282-bb748800-766d-11e9-917b-ada72c6e8214.png)

And I also see in the converted model, the Reshape layer input is not a fixed value, I understand that it is caused by the original model's reshape layer input is not a fixed value, but if I passed a fixed shape of input layer, the Reshape input should also be a fixed value, if the tool can optimize the following part(the Case input node), it could be nice:
![image](https://user-images.githubusercontent.com/1538922/57687737-8e74a500-766e-11e9-80dc-f76e33ed42b6.png)

**Comment by nbcsm** [comment]
for the 1st question, if i understand correctly, you are trying to only convert a part of original tf graph, right?
currently, we reply on tf itself to extract sub-graph
https://github.com/onnx/tensorflow-onnx/blob/1000b66d66e6332ceaaedde5664de2863a6e30ad/tf2onnx/tfonnx.py#L621-L622

for your case, the sub-graph you want to extract is inside a tf while loop.
i believe tf cannot extract the loop body alone because it depends on nodes outside of the loop.
you may give a try to call tf ```graph_util.extract_sub_graph``` to see how it works, i guess you will get extra nodes as well.

for the 2nd question, we have https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/optimizer/const_fold_optimizer.py to fold const nodes if possible.
currently, only fold Transpose is implemented.

contribution is welcomed.
for your case, seems adding support for Unsqueeze, Concat, Cast will work.

**Comment by fanghuaqi** [comment]
Thanks for your response. 
@nbcsm I take a look at graph in TensorBoard, but this node is not in a loop, it looks like this, it is the input node for following MobileNet backbone, the red node.
![image](https://user-images.githubusercontent.com/1538922/57911751-2cf54600-78bb-11e9-8543-2354d8259b4c.png)

Maybe it is a bug in the `graph_util.extract_sub_graph` function?

Thanks
Huaqi

**Comment by guschmue** [comment]
This should work - see here:
https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/ConvertingSSDMobilenetToONNX.ipynb
