### ISSUE TITLE
Tensorflow op MirrorPad is not supported

### ISSUE THREAD

**Issue by laobadao** [onnx/tensorflow-onnx#72]
't' is [[1, 2, 3], [4, 5, 6]].

  'paddings' is [[1, 1]], [2, 2]].

  'mode' is SYMMETRIC.

  rank of 't' is 2.

  pad(t, paddings) ==> 
[[2, 1, 1, 2, 3, 3, 2]

 [2, 1, 1, 2, 3, 3, 2]

 [5, 4, 4, 5, 6, 6, 5]

 [5, 4, 4, 5, 6, 6, 5]]

**Comment by pengwa** [comment]
currently onnx operator pad only support "constant", "edge", "reflect". So i think we cannot support SYMMETRIC easily right now. 

https://github.com/onnx/onnx/blob/master/docs/Operators.md#attributes-30

**Comment by guschmue** [comment]
https://github.com/onnx/tensorflow-onnx/pull/92

**Comment by pengwa** [comment]
@guschmue maybe we need keep this active? because currently we can only support limited "modes" that ONNX support for now. and "SYMMETRIC" is not supported by ONNX for now.

**Comment by Mina-am** [comment]
Is Symmetric mode is supported yet?

**Comment by TomWildenhain-Microsoft** [comment]
No, the onnx spec doesn't have it.  https://github.com/onnx/onnx/blob/master/docs/Operators.md#pad
Though it seems like we should be able to simulate it by padding with "edge" then "reflect".
Symmetric and Reflect seem very similar and they might even produce the same results.  @Mina-am have you tried just replacing the symmetrics with reflect?  If that doesn't work, I can try hacking support in tf2onnx by composing edge and reflect.  I'm not sure how the perf will be since we will be padding twice.

**Comment by Mina-am** [comment]
Thank you for the response.
Symmetric and Reflect are similar, but still different (see examples here: https://www.tensorflow.org/api_docs/python/tf/pad) 
 Yes, I think it's feasible by combining edge and reflect, but the problem is that tf does not have the 'edge' mode :|

**Comment by TomWildenhain-Microsoft** [comment]
Actually the edge/reflect sequence includes some extraneous rows and won't quite work.  What are the shapes of the tensors you are padding, and what are the pad amounts?  I can make a conversion using edge, reflect, and compress but it will be very inefficient.  What is the purpose of the pad in your model?  Do you pad just once, or is it done a lot?

**Comment by laobadao** [comment]
Great! Thanks
