### ISSUE TITLE
tf-onnx error using tf.contrib

### ISSUE THREAD

**Issue by danperazzo** [onnx/tensorflow-onnx#768]
Hello guys, I am new to onnx and I have got the following error when attempting to convert my model from tensorflow to onnx: tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'Resampler' in binary running on LAPTOP-Q3MCPN1A. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. 
That was because, in my model, I used some operations from tf.contrib. Is there some way to avoid this issue? Grateful for the help :))

**Comment by jignparm** [comment]
Any way to avoid the tf.contrib.resample operator in your model? This operator is not supported currently by the converter.

**Comment by danperazzo** [comment]
Nopes, it is essentiala :( I was trying to use the python API. Anyway to change it on the onnx code or maybe if I run it on th ePython API (when the tf.contrib is already running)

**Comment by jignparm** [comment]
This would require a custom entry in TF2ONNX for the conversion (e.g. https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/custom_opsets/ms.py#L32), and also you need an ONNX runtime to support the contrib op. 

Closing this issue for now. If this operator becomes more popular, we can revisit and propose it as an operator to the ONNX community. Not all TF ops are supported by TF2ONNX, usually because there's no corresponding ONNX operator.
