### ISSUE TITLE
Can I cut nodes before inputs I set?

### ISSUE THREAD

**Issue by ArtyZe** [onnx/tensorflow-onnx#856]
Hello,
       Thanks for your great job, but I just switch from mmdnn, I found a issue, that even when I set the input node as one middle node of my tf graph, ops not supported by onnx and before input node still come to error, tf2onnx will always ensure graph  complete?

**Comment by RandySheriffH** [comment]
@ArtyZe: so exactly what are the unsupported ops there?

**Comment by jignparm** [comment]
TF2ONNX should only be extracting the nodes needed between inputs and outputs (not the complete graph), based on the link below.

Even though you picked an input node in the middle of the graph, trying to bypass the unsupported ops, most likely the unsupported ops get pulled in anyways because they are still needed to produce the outputs correctly.

Can you pick another node as an input (a safer one, maybe closer to the output), that you know for sure will bypass the unsupported  operators? 

https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/tf_loader.py#L305

**Comment by ArtyZe** [comment]
@RandySheriffH 
Thanks, most time I need to skip preprocess and post process nodes like (input-mean)/variace before input.
@jignparm 
In https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/tf_loader.py#L305
function "extract_sub_graph" can not skip nodes before input_node which I set before.
I used function "strip_unused_lib.strip_unused" to get sub graph I want from orig graph finally.
Thanks

**Comment by jignparm** [comment]
Glad that "strip_unused_lib.strip_unused"  worked for you. I wonder if that might be a more appropriate function to include in the tf2onnx loader, versus "extract_sub_graph" -- it seems to have stricter removal of unrequired nodes.

**Comment by ArtyZe** [comment]
@jignparm 
I think so. As far it works good in my convert work,  I put this function in "tf_optimize”. 
I also added some code to change the input_node_name of sub graph to "Placeholder_orig", it seems more normal than "conv2/block/.....".
Thanks all you guys, you do really great job, thanks :)

**Comment by sullivak-kyra** [comment]
> @jignparm
> In https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/tf_loader.py#L305
> function "extract_sub_graph" can not skip nodes before input_node which I set before.
> I used function "strip_unused_lib.strip_unused" to get sub graph I want from orig graph finally.
> Thanks

@ArtyZe thanks for tip on using strip_unused. With that I'm able to strip off unneeded nodes, but I then get problems downstream when tensorflow imports the updated graph. Do you happen to have a code snippet of what did?
