### ISSUE TITLE
Conv2DBackpropInput's 1st input is assumed to be const

### ISSUE THREAD

**Issue by pengwa** [onnx/tensorflow-onnx#93]
The first input of Conv2DBackpropInput is the input_size. in current converter ,we assume it is a const, then we call get_tensor_value to get its value. This is because the corresponding ONNX operator https://github.com/onnx/onnx/blob/master/docs/Operators.md#convtranspose specify the input_size with attribute "output_shape". So we must give this attribute a explicit value during conversion. 

But in some case, the size is a dynamically generated, for example when I am converting style2paints tail model, here is an example: 

![image](https://user-images.githubusercontent.com/10530022/43332329-b07683fc-91fa-11e8-820d-b4f4f25ecb0d.png)

Though in this case, Conv2DBackpropInput  only depends on Shape value of "Sub" operation, but there is still a sub-graph to be handled (maybe we need calculate the result of pack, and make it as the input of Conv2DBackpropInput , but this sounds tricky).

This is very similar to https://github.com/onnx/tensorflow-onnx/issues/89.

**Comment by guschmue** [comment]
I think its a general issue with onnx that some inputs that should be dynamic are attributes.
We could maybe fix it for this specific issue but the next one will come soon after that.
For this issue - you can turn on constant folding which should take the sub out if both inputs are constant here:
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/tfonnx.py#L1372
I had kept this down since - I have seen issues on the tensorflow end with it but if it helps in this case we can take a look why this is not always working correctly (I belief there is a tensorflow issue on it).

**Comment by pengwa** [comment]
ok, let me try enable it and verify this.
