### ISSUE TITLE
Significant loading time with TensorRT compared to not

### ISSUE THREAD

**Issue by solarflarefx** [onnx/tensorflow-onnx#930]
**Describe the bug**
I built ONNX Runtime from source with TensorRT.  I am noticing that it's taking a significant amount of time to load the model and run the first inference as compared to not using TensorRT.

Upon trying to load the model, I get: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.

This cast down takes a long time.

- It takes ~35X longer to load with network with TRT compared to not using it
- It takes ~40X longer to run the first inference with TRT compared to not using it
- From thereon, inference is faster by ~20-25% with TRT compared to not using it

Is there something that can be done?  Anything I can do to pre-condition the ONNX model or would that cause more of a problem?  Is there another approach?  Do the numbers I am showing here seem normal or do they indicate that something is off?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-Bit
- Visual Studio: VS 2019
- API: C#
- TensorRT Version 7
- CUDA version: 10.1 w/ cuDNN

**Comment by jignparm** [comment]
Since you built from source, did you build in Debug mode (common)? If so, can you try out Release mode or RelWithDebInfo instead? 

It should not take 35X longer to load the model, or 40x longer to score the first example. If the session is started, it means the model should already be loaded into memory (either CPU or GPU memory).

Also, the fact that the second example is much faster than the first example, indicates that the model is OK (because the second example was fast), and there may be some unusual latency caused by the execution provider for the first example.

If Release mode compilation does not solve the issue, you may need to re-post this issue in the onnxruntime repository https://github.com/microsoft/onnxruntime?  This will require debugging the TensorRT execution provider directly.

**Comment by solarflarefx** [comment]
@jignparm Thanks for the quick reply.  I built with RelWithDebInfo.  OK I will post on ONNXRuntime github.
